#theme: jekyll-theme-minimal
#theme: jekyll-theme-slate
#remote_theme: pages-themes/minimal@v0.2.0
#remote_theme: pages-themes/tactile@v0.2.0
remote_theme: sproogen/modern-resume-theme
#plugins:
#- jekyll-remote-theme

# Personal info
name: Gustavo Rosales
email: rosalesagustavo@gmail.com
phone: (347)-839-5744

# Social links
github_username: okGus
linkedin_username: gus-rosales

# About Section
about_content: |+
  Started in high school learning to code, self taught, my school didn't have a course. My software project portfolio increased during college. 
  Created a mini-text based editor like with VIM like functionality. 
  
  Joined CUNY Tech Prep (CTP) were I was taught in demand technologies related  to data science and machine learning. Created a web based app designed to detect if an image was real or fake using machine learning. After CTP I 
  decided to make a web based bug/issue tracker, learn front-end and back-end, and new technologies and frameworks. Joined CodePath for an intermediate 
  cybersecurity course.

content:          
  - title: Education
    layout: list
    content: 
      - layout: left
        title: CUNY College of Staten Island
        sub_title: BA Computer Science
  - title: Projects
    layout: list
    content:
      - layout: left
        title: Weather Dashboard
        link: https://github.com/okGus/Weather-Dashboard
        link_text: Github
        description: Developed a web application to show current weather |
          Created a web application using HTML, CSS, Flask, and Python with the OpenWeatherMap API to display the current weather and forecasts based on zip code
      - layout: left
        title: Bug/Issue Tracker
        link: https://buugtracker.vercel.app/
        link_text: Site WIP
        description: |+
          Bug/Issue tracker
          From Jun 2022 to Oct 2022, I undertook a project to create a Bug/Issue Tracker. My responsibilities included designing and implementing a web application to enable users to track and manage bugs and issues.

          Using Next.js, I developed both the front-end and back-end components of the app. I also incorporated a 3rd party platform, Auth0, for login authentication and authorization. Additionally, 
          I utilized MongoDB to track and store the tickets, and Prisma to connect to the database. To ensure seamless client-server interactions, I leveraged tRPC technology.
  
  - title: Supporting Experience
    layout: list
    content:
      - layout: right
        title: Nordstrom Rack
        sub_title: Sales Person
        caption: Oct 2017 - Jun 2019

# About Section
#about_content: | # this will include new lines to allow paragraphs
#  Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.
#  You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
  
#content:
  
#  - title: Experience
#    layout: list
#    content:
#      - layout: right
#        title: Company name
#        sub_title: Job title
#        caption: Date Range (eg. November 2016 - present)
#        link: Link to company (optional)
#        quote: >
#          Short description of the company (optional)
#        description: | # this will include new lines to allow paragraphs
#          Description of role
#  - title: Education
#    layout: list
#    content:
#      - layout: top-right
#        title: Institution name
#        sub_title: Qualifications (eg. BA Performing Arts)
#        caption: Date Range (eg. 2016 - 2019)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)
