#theme: jekyll-theme-minimal
#theme: jekyll-theme-slate
#remote_theme: pages-themes/minimal@v0.2.0
#remote_theme: pages-themes/tactile@v0.2.0
remote_theme: sproogen/modern-resume-theme
#plugins:
#- jekyll-remote-theme

# Personal info
name: Gustavo Rosales
email: rosalesagustavo@gmail.com
phone: 

# Social links
github_username: okGus
linkedin_username: gus-rosales

# About Section
about_content: |+
  My name is Gustavo (Gus) Rosales, I have a bachelors degree in computer science, the first of my family to graduate college, self taught, curious, competitive, discipline among other things. 

  Started in high school learning to code in Java, my school didn't have a classes in programming so when I learned about College Now, a where I could take college classes for credit, I took that chance in Lehman College.
  
  Towards my end of my college years I joined CUNY Tech Prep (CTP) were I was taught in demand technologies related  to data science and machine learning. Created a web based app designed to detect if an image was real or fake using machine learning. After CTP I 
  decided to make a web based bug/issue tracker, learn front-end and back-end, and new technologies and frameworks. Joined CodePath for an intermediate 
  cybersecurity course.

  I like to learn new languages whether through advent of code, hackathons, or just personal projects.
working_on: |+
  Studying quantum computing through the year long program at Qubit x Qubit from The Coding School that is sponsored by Google AI where we get to learn the library Criq and learn about the quantum properties and how they are used in quantum computing.

  Currently a Software Developer at Entrepreneurs of Tomorrow via Virtual Interships - Unpaid
education_year: 2023
education: |+
    CUNY College of Staten Island
    
    B.S. Computer Science

content_projects:          
  - title: Projects
    layout: list
    content:
      - layout: left
        title: Unofficial Twitch API
        link: https://github.com/okGus/rapidTwitchAPI
        link_text: GH Link
        description: |+
          Created a web scraping solution for extracting data from Twitch.tv, emphasizing live channels within specific categories and popular content
        
          Utilized Playwright, chrome-aws-lambda, and Docker to implement advanced web scraping logic.
        
          Designed and executed a strategic approach to extract dynamic information including viewership statistics, video titles, and category details from Twitch.tv web pages
      - layout: left
        title: Portfolio Manager
        link: https://github.com/okGus/bb-tech-lab
        link_text: GH Link
        description: |+
          Implemented a market value calculation for different securities (positions, accounts, and portfolio)
          
          Designed an interactive graph of the market value over time of the different securities using BQPlo
      - layout: left
        title: Message Board
        link: https://github.com/okGus/message-board
        link_text: GH Link
        description: |+
          Developed PHP social web app in team of 2 for users post, likes, and comments on content shared content
          
          Stored users’ login, posts, and engagement activity in MySQL to save information for specific user access
          
          Built username availability checker for with JavaScript to differentiate accounts when signing up
      - layout: left
        title: Bug/Issue Tracker
        link: https://buugtracker.vercel.app/
        link_text: Site
        description: |+
          Bug/Issue tracker
          From Jun 2022 to Oct 2022, I undertook a project to create a Bug/Issue Tracker. My responsibilities included designing and implementing a web application to enable users to track and manage bugs and issues.

          Using Next.js, I developed both the front-end and back-end components of the app. I also incorporated a 3rd party platform, Auth0, for login authentication and authorization. Additionally, 
          I utilized MongoDB to track and store the tickets, and Prisma to connect to the database. To ensure seamless client-server interactions, I leveraged tRPC technology.
      - layout: left
        title: RealorFake
        link: https://github.com/okGus/realorfake
        link_test: GH Link
        description: |+
          Developed a web application between October and December 2021
          
          The application used machine learning to predict whether an image was altered or not
          
          Employed ResNet, a pre-trained model, to train thousands of real and fake images
          
          Used Python and Flask to build the web application
          
          Utilized Google Collab as the platform for training the model
      - layout: left
        title: Post COVID Ally, Hackathon
        link: https://github.com/okGus/post-covid-ally
        link_text: GH Link
        description: |+
          As a member of a team of three, I designed a web-based chat application to connect users and support each other's mental health after the pandemic. The application was developed using React for the frontend, providing a seamless user experience.
          To ensure user privacy, Firebase was used to store messages exchanged between users. This allowed users to connect with one another and provide emotional support in a safe and confidential environment.
          Our team named the application "Post-COVID Ally," and we showcased it during the CTP Hackathon in August 2021. The project was well-received and provided a valuable resource for individuals struggling with the mental health impacts of the pandemic.
      - layout: left
        title: Weather Dashboard
        link: https://github.com/okGus/Weather-Dashboard
        link_text: GH Link
        description: |+
          Developed a web application to display current weather and forecasts based on zip code
          Utilized HTML, CSS, Flask, and Python to create the application
          Integrated the OpenWeatherMap API to collect weather data
          Designed a user-friendly interface to display weather information
          Completed the project within the timeframe of June 2021 to August 2021
content_works:
  - title: Technical Related Experience
    layout: list
    content:
      - layout: left
        title: Google Software Engineering Program (G-SWEP) via ProjectBasta
        sub_title: Software Engineering Fellow
        caption: Mar 2023 - Sep 2023
        description: |+
          ● Engaged in a 10-week technical mentoring program with over 70 fellows, focusing on mastering foundational data structures and algorithms, while also honing interview skills to effectively showcase expertise\n
          
          ● Pair with Google SWE mentor with to coordinate technical and professional development through weekly check-ins on progress towards develop software engineering skill set\n
      - layout: left
        title: Bloomberg Engineering Princeton Tech Lab Fellow
        sub_title: Bloomberg LP
        caption: June 2023 - July 2023
        description: |+
          ● Selected to be 1 of 38 software engineers to attend a 3-day intensive Tech Lab at Bloomberg Engineering's Princeton Campus
            
          ● Collaborated with Bloomberg engineers + peers to build an Python based portfolio manager to keep track of Security, Position, Account, and Portfolio
            
          ● Attended interactive sessions focused technical SWE interview skills + tech talks
      - layout: left
        title: Data Science Fellow
        sub_title: CUNY Tech Prep
        caption: Jun 2021 – May 2022
        description: |+
          ● Learned in-demand technologies like Python 3, Jupyter Notebook, Pandas, Numpy, Scikit-learn, and SQL as well as industry best practices for exploratory data analysis (EDA)
            
          ● Utilized industry best practices such as feature engineering and machine learning techniques to create 2 applications, RealOrFake and ASL Gesture Recognition
            
          ● Live demoed RealOrFake app with team of 2 in front 20+ students and technical partners
# About Section
#about_content: | # this will include new lines to allow paragraphs
#  Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.
#  You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
  
#content:
  
#  - title: Experience
#    layout: list
#    content:
#      - layout: right
#        title: Company name
#        sub_title: Job title
#        caption: Date Range (eg. November 2016 - present)
#        link: Link to company (optional)
#        quote: >
#          Short description of the company (optional)
#        description: | # this will include new lines to allow paragraphs
#          Description of role
#  - title: Education
#    layout: list
#    content:
#      - layout: top-right
#        title: Institution name
#        sub_title: Qualifications (eg. BA Performing Arts)
#        caption: Date Range (eg. 2016 - 2019)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)
