#theme: jekyll-theme-slate
#remote_theme: pages-themes/minimal@v0.2.0
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme

content: 
  - title: Projects

name: Gustavo Rosales
email: rosalesagustavo@gmail.com
phone: (347)-376-3398
